### ISSUE TITLE
Script to scrape Amazon products

### ISSUE THREAD

**Issue by SANKET7738** [sanscript-tech/hacking-tools-scripts#10]
# Description 
 
Write a script to scrape amazon products. the function should take the name of the product and it should return the top 5 products for the query with their name, price, and ratings.

**Comment by AdityaJ7** [comment]
Hi @SANKET7738 I would like to work on this issue

**Comment by tejan-singh** [comment]
yes you can work on this issue.

**Comment by AdityaJ7** [comment]
@tejan-singh You can assign me back if you are ok with the pr that I submitted just now.

Thanks

**Comment by sujal111** [comment]
Please assign me this issue

**Comment by SANKET7738** [comment]
@sujal111 mention the language you want to use and start working on it.

**Comment by tejan-singh** [comment]
@sujal111 have you registered for the event? have you joined the slack channel?

**Comment by eternal-dreamer** [comment]
Can I work on this issue using python?

**Comment by tejan-singh** [comment]
Yes sure

**Comment by kritikaparmar-programmer** [comment]
Is someone working on this issue? @eternal-dreamer ?

**Comment by eternal-dreamer** [comment]
> Is someone working on this issue? @eternal-dreamer ?

No , I am not working on this issue now.

**Comment by TaniaMalhotra** [comment]
@yashaswibiyahut 
Can I take it if it's unassigned?
Would like to do it in python

**Comment by tejan-singh** [comment]
@kritikaparmar-programmer in which language you would like to work?

**Comment by HaripriyaB** [comment]
Can I take this if it's unassigned? I'd like to do it in **java**

**Comment by tejan-singh** [comment]
@HaripriyaB  you can work in java

**Comment by tejan-singh** [comment]
@TaniaMalhotra  You can work in python

**Comment by Ninjavin** [comment]
Hey @tejan-singh Can I work on this issue in NodeJS?

**Comment by HaripriyaB** [comment]
I'm not able to get the api to fetch product details... does anyone know which endpoint to be used?

**Comment by TaniaMalhotra** [comment]
Same here @HaripriyaB 
I did find [this](https://rapidapi.com/axesso/api/axesso-amazon-data-service1) one but it seems to be paid

**Comment by HaripriyaB** [comment]
One way is to use selenium automation. That will be almost similar in all the languages. @tejan-singh pls give your suggestion

**Comment by TaniaMalhotra** [comment]
The one I mentioned above ([https://rapidapi.com/axesso/api/axesso-amazon-data-service1](this)) does have a freemium too but requires me to enter the credit card number.
If it's possible for maintainers to get their own key during testing, I can proceed with this api.

**Comment by tejan-singh** [comment]
@TaniaMalhotra @HaripriyaB you can use BeautifulSoup

**Comment by tejan-singh** [comment]
@Ninjavin you can work in NodeJS

**Comment by tejan-singh** [comment]
@HaripriyaB if you cannot find other way, then you can solve it with selenium.
