### ISSUE TITLE
simple covid notifier

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#101]
- a simple script to remind every hour with no. of active cases, recovered cases and deaths in India or world whatever you find relevant.

hint: use some covid API

**Comment by Divyansh-20** [comment]
@tejan-singh Can I take up this issue? I'll be using Python as the scripting language

**Comment by tanweeralii** [comment]
Hey, I would like to work on this issue.

**Comment by tejan-singh** [comment]
go ahead! @tanweeralii

**Comment by tanweeralii** [comment]
Can I use web scrapping?

**Comment by muddhit** [comment]
Can i work on this issue as it seems unsolved ?

**Comment by tanweeralii** [comment]
I am going to do pr right now. Sorry

**Comment by tanweeralii** [comment]
Script is complete

**Comment by muddhit** [comment]
in which language are you working on ? @tanweeralii

**Comment by tanweeralii** [comment]
Python
