### ISSUE TITLE
a face detection script

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#103]
use open cv

**Comment by kritikaparmar-programmer** [comment]
Hey @tejan-singh I want to work on this issue. Please assign me

**Comment by yashaswibiyahut** [comment]
@kritikaparmar-programmer I have already assigned issues to you. Please complete them first then you can work on more.

**Comment by Ninjavin** [comment]
Hi @tejan-singh Please assign this to me.
