### ISSUE TITLE
a script to get geolocation using IP address

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#106]
- you need to take input as IP address and give output as latitudes and longitudes.

**Comment by Namyalg** [comment]
I would like to work on this in Python

**Comment by muddhit** [comment]
I would like to work on this in Java

**Comment by tejan-singh** [comment]
Yes you can do it in java. @Mukulbaid63

**Comment by Nibba2018** [comment]
@tejan-singh I would like to work on this issue if it goes stale.
