### ISSUE TITLE
attend automatic zoom calls

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#108]
- A zoom bot that automatically joins zoom calls for you

**Comment by kritikaparmar-programmer** [comment]
Hey @tejan-singh Can I take up this issue?

**Comment by yashaswibiyahut** [comment]
@kritikaparmar-programmer I have already assigned issues to you. Please complete them first then you can work on more.

**Comment by tejan-singh** [comment]
Yes, now you can work on this. @kritikaparmar-programmer

**Comment by avnoor-488** [comment]
@tejan-singh can i work upon this?
