### ISSUE TITLE
Password Cracker Using Python

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#11]
hint :- you can use hashlib for this.

**Comment by harshareddy794** [comment]
Can I create a python script that uses an excel sheet as a dataset to crack sha256 and MD5 hashed passwords? @tejan-singh 
I am using hashlib for this. Can you explain this in a brief? 
Thank you

**Comment by tejan-singh** [comment]
Yes you can use excel file, csv,or txt to read payloads

**Comment by harshareddy794** [comment]
I would like to work on this issue @tejan-singh 
Please assign me

**Comment by yashaswibiyahut** [comment]
Go for it @harshareddy794

**Comment by harshareddy794** [comment]
Thanks @yashaswibiyahut
