### ISSUE TITLE
instagram bot

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#110]
list all the accounts that you follow, which don't follow you back.

**Comment by HaripriyaB** [comment]
Can I take this up?

**Comment by yashaswibiyahut** [comment]
Grab it @HaripriyaB

**Comment by HaripriyaB** [comment]
Hey @yashaswibiyahut @tejan-singh  I think the functionality of getting any instagram account(be it own or others account) followers/following is removed recently.
So I don't think there is a way to get the following accounts details. correct me if I'm wrong.

**Comment by tejan-singh** [comment]
Are you sure? Can you share the resource where did you get the news?

**Comment by HaripriyaB** [comment]
> Are you sure? Can you share the resource where did you get the news?

As far as I browsed ...
https://developers.facebook.com/docs/instagram-api This is the official doc, where there is no mention of any endpoint for accessing followers or following info.
 
If you can help in finding a way to do this it would be great.

**Comment by kana800** [comment]
@HaripriyaB  I think Instagram close their API, Maybe you can try [selenium](https://selenium-python.readthedocs.io/). check out this [video](https://www.youtube.com/watch?v=d2GBO_QjRlo)

**Comment by HaripriyaB** [comment]
> @HaripriyaB  I think Instagram close their API, Maybe you can try [selenium](https://selenium-python.readthedocs.io/). check out this [video](https://www.youtube.com/watch?v=d2GBO_QjRlo)

This is cool. I can do this coz I have experience using selenium. Thanks for the help!!
