### ISSUE TITLE
create a file hasher using python with different hashing methods.

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#12]
it should include hashes like md5, sha etc
hint: you can use hashlib.

**Comment by harshareddy794** [comment]
@tejan-singh  Can I work on this issue?

**Comment by tejan-singh** [comment]
yes you can work on this.

**Comment by harshareddy794** [comment]
My PR got merged but the issue is still open can you check @tejan-singh
