### ISSUE TITLE
a simple python script to shut down your System

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#14]

**Comment by AdityaJ7** [comment]
Hi @tejan-singh can I take this issue?

**Comment by tejan-singh** [comment]
i have already assigned issues to you. Please complete them first then you can work on more.

**Comment by Nagasuruthika** [comment]
I'd like to work on this

**Comment by tejan-singh** [comment]
assigned to you @Nagasuruthika
