### ISSUE TITLE
Telegram Automation

### ISSUE THREAD

**Issue by Namyalg** [sanscript-tech/hacking-tools-scripts#160]
**Is your feature request related to a problem? Please describe.**
With this script, messages can automatically be sent on Telegram from the Command Line

**Describe the solution you'd like**
Using the Selenium module with Python, this task can be automated

**Comment by harshareddy794** [comment]
Can I work on this?

**Comment by Namyalg** [comment]
I have raised this issue and would like to work on it @tejan-singh

**Comment by tejan-singh** [comment]
Great! Go for it @Namyalg
