### ISSUE TITLE
Counting days 

### ISSUE THREAD

**Issue by yashaswibiyahut** [sanscript-tech/hacking-tools-scripts#166]
**Describe the solution you'd like**
Script for counting how many days there is left for any given date(birthday).

**Comment by Nibba2018** [comment]
@yashaswibiyahut I would like to work on this.

**Comment by Sapna2001** [comment]
Can I work on this?

**Comment by Sapna2001** [comment]
@yashaswibiyahut can I do this in JavaScript?

**Comment by SANKET7738** [comment]
@Sapna2001 go-ahead

**Comment by TaniaMalhotra** [comment]
Can I work on this in C++? @yashaswibiyahut @tejan-singh

**Comment by Tejas1510** [comment]
Can I work on this using HTML,css, and Javascript creating a mini website @yashaswibiyahut @SANKET7738

**Comment by tejan-singh** [comment]
@Tejas1510 you can work on this.

**Comment by tejan-singh** [comment]
@TaniaMalhotra you can work on this issue.
