### ISSUE TITLE
Certificate Generation Script

### ISSUE THREAD

**Issue by Tejas1510** [sanscript-tech/hacking-tools-scripts#174]
**Is your feature request related to a problem? Please describe.**
Generating a ton of certificates for any occasion is quite tedious if you're not familiar with the concept of automation. Well, you won't have to worry anymore because this script will do all the heavy lifting for you.

**Describe the solution you'd like**
I wish to generate a python script that will take a input file as all the names of people and will generate that many certificate

**Describe alternatives you've considered**

**Additional context**

**Comment by tejan-singh** [comment]
Great! Go ahead
