### ISSUE TITLE
to use Steganography to Hide Secret Data in Images in Python

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#180]
- inputs required include an image, a message to encode, and function to perform.
- key generation function can be implemented inside main file.
- key should be generated in seperate file which can be used to decode image.
- you also need to generate key to encode and decode message.
- hint: use opencv

**Comment by Nibba2018** [comment]
@tejan-singh I would like to work on this.

**Comment by tejan-singh** [comment]
Yes, go ahead. @Nibba2018
