### ISSUE TITLE
script to generate checksums from md5, sha1, sha224, sha256, sha384, and sha512 for a file

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#186]
hint: use os sys hmac base64 hashlib argparse

**Comment by Nibba2018** [comment]
Hi @tejan-singh , I would like to work on this.

**Comment by Nibba2018** [comment]
Also how was your exam? :smile:

**Comment by tejan-singh** [comment]
Go for it. @Nibba2018

**Comment by tejan-singh** [comment]
@Nibba2018 i found you have already 2 assigned issues. I am assigning you from this.

**Comment by Nibba2018** [comment]
@tejan-singh I have already solved the issues that were assigned to me.

**Comment by tejan-singh** [comment]
okey, let me check.

**Comment by tejan-singh** [comment]
@Nibba2018  okey,  you can work on this.

**Comment by Nibba2018** [comment]
@tejan-singh done.
