### ISSUE TITLE
a simple YouTube video Downloader

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#202]
- you can implement this in different languages. Comment down the language you want to work in.

**Comment by TaniaMalhotra** [comment]
Can I work in python?

**Comment by tejan-singh** [comment]
yes please! @TaniaMalhotra

**Comment by Ninjavin** [comment]
Please assign me for NodeJS

**Comment by Tejas1510** [comment]
Can i work on it?

**Comment by tejan-singh** [comment]
@Ninjavin yes you can work in NodeJs

**Comment by tejan-singh** [comment]
@Tejas1510 in which language you want to work in ?

**Comment by Tejas1510** [comment]
can I make it in python? @tejan-singh

**Comment by tejan-singh** [comment]
@Tejas1510 It has been submitted for python.
