### ISSUE TITLE
Fetch Current Weather using WeatherMapApi

### ISSUE THREAD

**Issue by Tejas1510** [sanscript-tech/hacking-tools-scripts#205]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I wish to use weathermapApi for fetching the current weather and will make a frontend gui in python with the help of tkinter to take input as the city and display the final output

**Describe alternatives you've considered**

**Additional context**

**Comment by tejan-singh** [comment]
Very nice, Go for it.

**Comment by Tejas1510** [comment]
@tejan-singh can I work on it again making the complete code from scratch

**Comment by tejan-singh** [comment]
This issue is now invalid. This cannot be assigned to you again.

**Comment by Ninjavin** [comment]
Hey @tejan-singh Can I work on this issue in NodeJS or is the issue completely invalid now?
