### ISSUE TITLE
News Voice assistant to listen to your favourite news

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#218]
use https://newsapi.org/register

**Comment by TaniaMalhotra** [comment]
Can I take this up?

**Comment by tejan-singh** [comment]
yes, go for it! @TaniaMalhotra

**Comment by TaniaMalhotra** [comment]
@tejan-singh I've written a python script in my current PR
Can I also work on the same issue in node js?

**Comment by tejan-singh** [comment]
@TaniaMalhotra you can work in NodeJS.
