### ISSUE TITLE
a pdf watermark generator

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#219]
hint: use pyPDF

**Comment by sejalshri** [comment]
i would like to work on this issue.please assign.

**Comment by tejan-singh** [comment]
Yes, you can work on this issue @sejalshri

**Comment by muddhit** [comment]
assign me for python @tejan-singh

**Comment by tejan-singh** [comment]
@Mukulbaid63 you can work in Python
