### ISSUE TITLE
A Simple keylogger for linux

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#23]

**Comment by HabibRh26** [comment]
Hello, I want to take this task, my preferred language is python. thanks

**Comment by yashaswibiyahut** [comment]
Go for it @HabibRh26

**Comment by Nibba2018** [comment]
@tejan-singh I would like to work on this.

**Comment by tejan-singh** [comment]
you can work on this! @Nibba2018
