### ISSUE TITLE
CodeChef Scrapper

### ISSUE THREAD

**Issue by Tejas1510** [sanscript-tech/hacking-tools-scripts#235]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I wish to create a codechef scrapper that will fetch details about the recent codechef contest.

**Describe alternatives you've considered**

**Additional context**

**Comment by tejan-singh** [comment]
Please try other topics other than scrapping or automation. We have already created many of these kinds of issues.

**Comment by Tejas1510** [comment]
@tejan-singh Sir Sure i will try to think of some other topic
