### ISSUE TITLE
Convert Image to Sketch 

### ISSUE THREAD

**Issue by sharur7** [sanscript-tech/hacking-tools-scripts#239]
**Is your feature request related to a problem? Please describe.**

To convert the original image into a black and white sketched image

**Describe the solution you'd like**

OpenCV libraries can be used to convert a normal image into a black and white sketched image

**Describe alternatives you've considered**

**Additional context**

The code will be written in Python

I would like to work on this issue  @tejan-singh @yashaswibiyahut  @balapriyac @SANKET7738

**Comment by kuldip11** [comment]
Can i work on this issue?

**Comment by Tejas1510** [comment]
@yashaswibiyahut can i go with the concept of HTML5 and canvas
Please assign me on this issue
