### ISSUE TITLE
Internet Connection Checker

### ISSUE THREAD

**Issue by Tejas1510** [sanscript-tech/hacking-tools-scripts#247]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A python program to check if your system has an internet connection using socket and time module in python

**Describe alternatives you've considered**

**Additional context**

**Comment by tejan-singh** [comment]
This issue has already been submitted

**Comment by Tejas1510** [comment]
Ok @tejan-singh 
will try to work on some other issue
