### ISSUE TITLE
Morse Code Converter

### ISSUE THREAD

**Issue by Tejas1510** [sanscript-tech/hacking-tools-scripts#250]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I wish to learn encryption and decryption so as to implement the solution, the code may text words as input and convert it corresponding morse code while the reverse is also true

**Describe alternatives you've considered**

**Additional context**

**Comment by SANKET7738** [comment]
Mention the language

**Comment by Tejas1510** [comment]
@SANKET7738 Sir i would do it in python

**Comment by SANKET7738** [comment]
Assigned to you @Tejas1510

**Comment by tejan-singh** [comment]
@Tejas1510 you can work in java

**Comment by Tejas1510** [comment]
@tejan-singh Sir i have already generated a PR for it and my pull request got merged
I ask you to assign me java on the issue #256
