### ISSUE TITLE
scan the current directory and all subdirectories and display the size

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#255]

**Comment by Sapna2001** [comment]
Can I work on this?

**Comment by tejan-singh** [comment]
@Sapna2001 you can work on this but please mention language your working in comments

**Comment by Sapna2001** [comment]
I will be working in python.

**Comment by japneetkaurbhatia** [comment]
Sir, I want to try this in C

**Comment by Tejas1510** [comment]
@tejan-singh can I work in java?

**Comment by tejan-singh** [comment]
@Tejas1510 you can work in java

**Comment by tejan-singh** [comment]
@japneetbhatia you can work in C.

**Comment by japneetkaurbhatia** [comment]
Sir, I already created pull request for the same around an hour ago

**Comment by tejan-singh** [comment]
@japneetbhatia but the issue was not assigned to you. How could you send PR? Next time, please wait for the issue to be assigned then send PR, okey
