### ISSUE TITLE
to count number of files and sub directories in a directory

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#256]
output can be like:

Number of files:
Number of Directories:
Total:

**Comment by Tejas1510** [comment]
@tejan-singh can I work on this

**Comment by tejan-singh** [comment]
@Tejas1510 you have already 2 assigned issues

**Comment by Tejas1510** [comment]
No Sir i have only one issue assigned
For other t have created a pull request
So I have only one issue one I am finding it somewhat hard to code for it 
Can you please assign me
I want to do in Java
@tejan-singh Sir

**Comment by anut123** [comment]
Can I work on this issue in python?

**Comment by tejan-singh** [comment]
@anut123 yes you can work on this in python

**Comment by tejan-singh** [comment]
Okey @Tejas1510 you can work in java.

**Comment by Siddhant-K-code** [comment]
tool for github or to count locally ?

**Comment by Siddhant-K-code** [comment]
if it is for local use, i can create one using python

**Comment by tejan-singh** [comment]
@Siddhant-K-code its for local directory. Its been assigned for python. You can choose another language.
