### ISSUE TITLE
to get weather details for current city which include temperature,weather and windspeed.

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#258]
hint: use api.openweathermap.org

**Comment by muddhit** [comment]
I want to work on it in Javascript.Plz assign me @tejan-singh

**Comment by Tejas1510** [comment]
@tejan-singh can i go for it
This time the complete code will be prepare from scratch and wish to make a small website using HTML,css and javascript fetching the data from the provided api

**Comment by muddhit** [comment]
I am also going to same thing,that's why i requested @tejan-singh to assign me for javascript. FCFS.

**Comment by Tejas1510** [comment]
Ok @Mukulbaid63 
if Sir allows both of us to do in javascript then we may prepare our separate code which will have a different UI and look or I will go in python then
No worries
Happy Coding

**Comment by Ninjavin** [comment]
Can you assign me? I can do this in Python @tejan-singh

**Comment by tejan-singh** [comment]
@Mukulbaid63 you can work in JavaScript

**Comment by tejan-singh** [comment]
@Ninjavin you can work in python

**Comment by tejan-singh** [comment]
@Tejas1510 I can only assign one person to work on one language only.

**Comment by Tejas1510** [comment]
ok @tejan-singh Sir

**Comment by Nibba2018** [comment]
@tejan-singh I would like to work on this in C

**Comment by TaniaMalhotra** [comment]
Would like to work in c++

**Comment by tejan-singh** [comment]
@Nibba2018 go ahead

**Comment by tejan-singh** [comment]
@TaniaMalhotra  go ahead
