### ISSUE TITLE
download and save a webpage as pdf

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#259]
hint: use argparse, pyppdf, re, pyppeteer

**Comment by kuldip11** [comment]
Assign me for python

**Comment by Ninjavin** [comment]
Can you assign me? I can do this in NodeJS @tejan-singh

**Comment by tejan-singh** [comment]
@kuldip11 you can work in python.

**Comment by tejan-singh** [comment]
@Ninjavin actually you already have 2 assigned issues.

**Comment by Ninjavin** [comment]
@tejan-singh Yeah I saw that right now. No problem.

**Comment by Ninjavin** [comment]
Hey @tejan-singh I have solved one of the issues and submitted a PR. So if you want you can assign this to me :)

**Comment by tejan-singh** [comment]
@Ninjavin okey, you can work in NodeJS

**Comment by TaniaMalhotra** [comment]
Can I take it in python?

**Comment by tejan-singh** [comment]
@TaniaMalhotra  you can work in python

**Comment by TaniaMalhotra** [comment]
@tejan-singh  Sir can I use [pdfkit](https://pdfkit.org/)?
Looks like it has direct methods for this purpose

**Comment by tejan-singh** [comment]
@TaniaMalhotra Ok, you can work if you find a solution.

**Comment by TaniaMalhotra** [comment]
@tejan-singh sir
Can I also do this in JAVA?
