### ISSUE TITLE
script to find admin panel of a website

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#27]
hint: you can use sys, requests and time modules.

**Comment by kritikaparmar-programmer** [comment]
Hey @tejan-singh please assign me this issue.

**Comment by yashaswibiyahut** [comment]
`Go for it @kritikaparmar-programmer `

**Comment by Ninjavin** [comment]
Hey @yashaswibiyahut Please assign me!

**Comment by tejan-singh** [comment]
@Ninjavin go for it.
