### ISSUE TITLE
script to make your images circular.

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#276]
- ask for diameter as input in pixel

**Comment by Sapna2001** [comment]
Can I take this?

**Comment by tejan-singh** [comment]
@Sapna2001 please specify the language you will be working in?

**Comment by Sapna2001** [comment]
I will be working in python.

**Comment by Tejas1510** [comment]
@tejan-singh can I work with HTML and javascript

**Comment by yashaswibiyahut** [comment]
@Tejas1510 yes you can

**Comment by Tejas1510** [comment]
@yashaswibiyahut mam please add the assigned label so I can go forward with the work
