### ISSUE TITLE
script to find/remove duplicate files from the user specified directory

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#277]

**Comment by TaniaMalhotra** [comment]
Can I take this?

**Comment by tejan-singh** [comment]
@TaniaMalhotra in which language??

**Comment by Tejas1510** [comment]
@tejan-singh can i work in python

**Comment by TaniaMalhotra** [comment]
@tejan-singh sir can I write a shell script for the same? 
If not, then I can work in python

**Comment by tejan-singh** [comment]
@TaniaMalhotra choose any one you like.

**Comment by Tejas1510** [comment]
@TaniaMalhotra if you are going for shell script can I work in python
can you please assign me @tejan-singh Sir, @SANKET7738 Sir, @yashaswibiyahut Mam

**Comment by TaniaMalhotra** [comment]
Um I'm sorry 😥
I started working in python coz I didn't find any separate folder for shell scripts
If you really really want it in python, then no problems
I'll start over :)

**Comment by Tejas1510** [comment]
@TaniaMalhotra no-no, Go ahead
I haven't started with the code so will make it in some other language

**Comment by Tejas1510** [comment]
@tejan-singh can i go for it  in Java
Please assign me

**Comment by tejan-singh** [comment]
@Tejas1510 You can work in Java
