### ISSUE TITLE
create a automated script to check for XSS on a website.

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#28]
- you must read payloads from an XSS payload text file.
- hint: you can use requests and subprocess modules in python.

**Comment by srimanikantapalakollu** [comment]
I want to work on this issue.

**Comment by yashaswibiyahut** [comment]
Go for it @srimani-programmer

**Comment by Ninjavin** [comment]
Hey @tejan-singh This sounds interesting. Please assign me.

**Comment by tejan-singh** [comment]
@Ninjavin go for it.
