### ISSUE TITLE
to make a digital watch

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#286]
- for c c++ python java etc use GUI
- for javascript use html css and javascript

**Comment by kuldip11** [comment]
Can you please assign me for python?

**Comment by Ninjavin** [comment]
Hey @tejan-singh Please assign me for JS

**Comment by tejan-singh** [comment]
@Ninjavin you can work in JS

**Comment by tejan-singh** [comment]
@kuldip11 Commenting on every issue will create confusing for us to find which issue you would really like to work on.

**Comment by Tejas1510** [comment]
@tejan-singh can i make it in React and Bootstrap

**Comment by kuldip11** [comment]
@tejan-singh ok sorry for that.

**Comment by muddhit** [comment]
Assign me for python

**Comment by HaripriyaB** [comment]
I would like to work on this. Language : Java

**Comment by SANKET7738** [comment]
> @tejan-singh can i make it in React and Bootstrap

React is in JS only and JS is already taken by other participants.

**Comment by SANKET7738** [comment]
@Mukulbaid63 you can work in Python

**Comment by SANKET7738** [comment]
@HaripriyaB  you can work in Java

**Comment by Tejas1510** [comment]
@SANKET7738 Sir but the implementation will be quite different ,I would be using the concept of useState to store the time at each instance which will be very different from vanilla javascript
So I would request you to assign me this
Thank you

**Comment by tejan-singh** [comment]
@Tejas1510 please understand this is a hacking project not web development project. We can accept solutions in particular programming languages only.

**Comment by Tejas1510** [comment]
@tejan-singh Sure Sir 
Thanks for explaining 
Would work on something else
