### ISSUE TITLE
Downlaods all the videos from instagram post. 

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#296]
User needs to provide instagram post id as parameter

**Comment by Tejas1510** [comment]
Can I go for it in python @tejan-singh

**Comment by muddhit** [comment]
Please assign me for python @tejan-singh @yashaswibiyahut @balapriyac @SANKET7738

**Comment by muddhit** [comment]
logging in shouldn't be necessary,right?Can you guide me a little for solving this issue?Which library should i use? is the url itself the post id?

**Comment by tejan-singh** [comment]
it is only possible for public profiles only.Your URL is the post id. You will only need 
import sys
import requests
import time
import urllib.request
import os

**Comment by muddhit** [comment]
ok got it.

**Comment by HaripriyaB** [comment]
@tejan-singh If this issue is still unsolved I would like to take this. Language:  Python

**Comment by tejan-singh** [comment]
@HaripriyaB you can work on this in python.
