### ISSUE TITLE
a sudoku solver

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#298]
- take input of sudoku to solve as matrix and print solved output.

**Comment by Sapna2001** [comment]
Can I work on this in java?

**Comment by Tejas1510** [comment]
Can I work in python?

**Comment by tejan-singh** [comment]
@Sapna2001 you can work in java

**Comment by tejan-singh** [comment]
@Tejas1510  You can work in python

**Comment by Ninjavin** [comment]
@tejan-singh Can I go for this in JS?

**Comment by tejan-singh** [comment]
@Ninjavin you can work in JS
