### ISSUE TITLE
Implement Substitution Cipher 

### ISSUE THREAD

**Issue by SANKET7738** [sanscript-tech/hacking-tools-scripts#3]
# Description
Write a Script to implement substitution cipher. The function should take the message and key from the user and return the encrypted message.

**Comment by Namyalg** [comment]
I would like to work on this

**Comment by tejan-singh** [comment]
you can start working on this.

**Comment by Namyalg** [comment]
Can the key be accepted as a text file or csv file?

**Comment by Namyalg** [comment]
Okay, will do!
