### ISSUE TITLE
Write code for Primality Testing

### ISSUE THREAD

**Issue by balapriyac** [sanscript-tech/hacking-tools-scripts#30]
-  Check if number is prime
-  Use simple approach first
-  Fermat Primality Test

**Comment by ultraUnicorn74** [comment]
I would like to work on this issue.please assign me.

**Comment by balapriyac** [comment]
Could you pls specify language you'd like to code in

**Comment by ultraUnicorn74** [comment]
@balapriyac i would like to code in c++.

**Comment by tejan-singh** [comment]
@richabh456  are you working on this issue?

**Comment by ultraUnicorn74** [comment]
@tejan-singh  yes sir it got merged.
