### ISSUE TITLE
merge 2 pdfs into single pdf

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#300]

**Comment by Tejas1510** [comment]
I would like to go for it in python @tejan-singh Sir

**Comment by Ninjavin** [comment]
Hey @tejan-singh Can I go for it in NodeJS?

**Comment by HaripriyaB** [comment]
I would like to pick this up. Language : Java

**Comment by tejan-singh** [comment]
@HaripriyaB you can work in java
