### ISSUE TITLE
Implement Modular Exponentiation

### ISSUE THREAD

**Issue by balapriyac** [sanscript-tech/hacking-tools-scripts#31]
- Include importance of modular exponentiation in cryptography in README while raising PR
-  Try to come up with more than one solution 
- Compare the time and space complexity of each approach

**Comment by AdityaJ7** [comment]
Hi @balapriyac , I would like to work on this

**Comment by balapriyac** [comment]
Sure  which language would you prefer?

**Comment by AdityaJ7** [comment]
Python @balapriyac

**Comment by balapriyac** [comment]
Sure, I shall assign.
