### ISSUE TITLE
Script to scrape your favourite e-learning platform

### ISSUE THREAD

**Issue by balapriyac** [sanscript-tech/hacking-tools-scripts#32]
- Use any library that you're comfortable with
- Get info of the courses offered
- Cleaned csv file containing course name, key skills covered, instructor name/institute and the urls associated with them

**Comment by Shubham-1105** [comment]
I want to work on this

**Comment by yashaswibiyahut** [comment]
Go for it @Shubham-1105

**Comment by kritikaparmar-programmer** [comment]
Do we have to scrape just a single website like Udemy? @balapriyac

**Comment by balapriyac** [comment]
Hi, yes, if your script can scrape a particular platform like
Coursera,edx,Udemy, Udacity etc (whichever you like best) it'll be fine.

However the url is a variable and the script should be generic in that we
should be able to get course details from any e learning platform

**Comment by Tejas1510** [comment]
Can i work on this? @yashaswibiyahut @balapriyac

**Comment by tejan-singh** [comment]
@Tejas1510 you can work on this issue.

**Comment by Tejas1510** [comment]
@tejan-singh can i please unassigned me 
I tried making the code but the selected website is not responding correctly while scrapping
Thank you
