### ISSUE TITLE
Chinese Remainder Theorem

### ISSUE THREAD

**Issue by balapriyac** [sanscript-tech/hacking-tools-scripts#33]
- Understand CRT
- Implement in you programming language of choice
- Relevance in cryptography

**Comment by muddhit** [comment]
Please assign me it for JAVA!!

**Comment by balapriyac** [comment]
Sure

**Comment by avnoor-488** [comment]
can you please assign me it for c++?

**Comment by sejalshri** [comment]
@balapriyac  I can implement it in C or Java.please assign.

**Comment by muddhit** [comment]
@sejalshri its already assigned for java to me

**Comment by muddhit** [comment]
please assign the java to me i will complete by tomorrow

**Comment by muddhit** [comment]
i have still 1 day left according to the guidelines.Please re assign to me @tejan-singh

**Comment by tejan-singh** [comment]
@Mukulbaid63 You can work on this issue. You have time till midnight.

**Comment by tejan-singh** [comment]
@avnoor-488 I cannot find you in the slack group. Please go though the contribution guidelines once.

**Comment by tejan-singh** [comment]
@sejalshri you can work in C

**Comment by muddhit** [comment]
I have submitted the PR, please mention required changes,if any.
