### ISSUE TITLE
Ascii Image Converter

### ISSUE THREAD

**Issue by Tejas1510** [sanscript-tech/hacking-tools-scripts#336]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The code takes an image as input and converts it to a corresponding image having all ASCII characters.The script will be written in python. I am attaching a sample output which I wish to achieve as output

![image](https://user-images.githubusercontent.com/64543913/98775837-e6cb6500-2413-11eb-8517-7930984434ad.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Tejas1510** [comment]
@tejan-singh Sir , @SANKET7738 Sir @yashaswibiyahut Mam please assign me this issue in python

**Comment by SANKET7738** [comment]
@Tejas1510  assigned to you
