### ISSUE TITLE
to find if a file exists on the system with the specified name

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#341]

**Comment by TaniaMalhotra** [comment]
Can I take it in python?

**Comment by TaniaMalhotra** [comment]
@tejan-singh sir
Is it that we'll give a path of the file and the script will check whether it exists or not?

**Comment by tejan-singh** [comment]
You first need to ask path from user. Then you need to ask file name from user to search for in that particular path.

**Comment by TaniaMalhotra** [comment]
Ok 
Please assign this to me in python

**Comment by tejan-singh** [comment]
@TaniaMalhotra you can work in python.
