### ISSUE TITLE
a email bomber

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#344]
- while testing use temporary mail services like yopmail or tmpmail

**Comment by TaniaMalhotra** [comment]
Can I take it in python?

**Comment by tejan-singh** [comment]
@TaniaMalhotra you can work on this,

**Comment by Ninjavin** [comment]
@tejan-singh Can you assign this to me for NodeJS?

**Comment by tejan-singh** [comment]
@Ninjavin you can work in NodeJs
