### ISSUE TITLE
A simple script to print random motivational quotes.

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#346]
you can use any api or you can refer this url https://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en

**Comment by TaniaMalhotra** [comment]
Can I take this in python?

**Comment by Sapna2001** [comment]
Can I do this in JavaScript?

**Comment by HaripriyaB** [comment]
I would like to take this up. Language:Java

**Comment by tejan-singh** [comment]
@TaniaMalhotra you can work in python

**Comment by tejan-singh** [comment]
@HaripriyaB you can work in Java

**Comment by tejan-singh** [comment]
@Sapna2001 you can work in javascript
