### ISSUE TITLE
Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by SANKET7738** [sanscript-tech/hacking-tools-scripts#35]
# Description 
Create a CONTRIBUTING.md mentioning all the guidelines mentioned on the slack channel.  Mention proper instructions and guidelines to follow right from forking the repo to submitting a PR. Added screenshots would be helpful.

**Comment by Sapna2001** [comment]
@SANKET7738 can I work on this issue?

**Comment by tejan-singh** [comment]
are you a participant?

**Comment by Sapna2001** [comment]
@tejan-singh Yes.

**Comment by yashaswibiyahut** [comment]
Go for it @Sapna2001
