### ISSUE TITLE
Currency Converter

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#376]
use API to get real-time exchange rates: https://api.exchangerate-api.com/v4/latest/USD

for easy: simple CLI app 
for the medium: GUI app

**Comment by muddhit** [comment]
I want to do it in JavaScript in medium level implementation

**Comment by tejan-singh** [comment]
@Mukulbaid63 you can work in JavaScript

**Comment by Sapna2001** [comment]
Can I work on JavaScript easy version.

**Comment by Ninjavin** [comment]
@tejan-singh I would like to go for Python Easy Version if possible.

**Comment by tejan-singh** [comment]
@Sapna2001 you can work on JavaScript CLI

**Comment by tejan-singh** [comment]
@Ninjavin you can work on python CLI

**Comment by yagizhanNY** [comment]
Hi, I would like to work on Python medium version, if it is possible?

**Comment by tejan-singh** [comment]
@yagizhanNY have you registered for the event and joined the slack channel?
