### ISSUE TITLE
Script to accept bulk LinkedIn Connection requests.

### ISSUE THREAD

**Issue by SANKET7738** [sanscript-tech/hacking-tools-scripts#4]
# Description 
Write a script to accept bulk LinkedIn connection requests.

**Comment by Namyalg** [comment]
I would like to attempt working on this issue

**Comment by tejan-singh** [comment]
@Namyalg issues are already assigned to you. Please complete those issue then we can assign you more.

**Comment by ShruthiShriT** [comment]
can i work on this issue?

**Comment by SANKET7738** [comment]
@ShruthiShriT mention the language you will be using.

**Comment by sanjibansg** [comment]
Do assign me this issue if available.

**Comment by SANKET7738** [comment]
guys mention the language you will be using while asking for a PR. Anyone who is presently working on this please comment on the language you are using.

**Comment by ShruthiShriT** [comment]
@SANKET7738 i am using javascript

**Comment by tejan-singh** [comment]
@ShruthiShriT you can work in JavaScript.

**Comment by ShruthiShriT** [comment]
@tejan-singh ok
