### ISSUE TITLE
Strong password detection.

### ISSUE THREAD

**Issue by yashaswibiyahut** [sanscript-tech/hacking-tools-scripts#41]
Make a Python Script that detects a strong password.

**Comment by Abhijeet-sonkar** [comment]
Can I work on this issue?

**Comment by yashaswibiyahut** [comment]
Go for it @Abhijeet-sonkar

**Comment by Abhijeet-sonkar** [comment]
Can you provide the specification for Strong Password?

**Comment by yashaswibiyahut** [comment]
Conditions for Strong Password:
1) length of the entered password should not be greater than 15 
2) The entered password should have at least one uppercase letter  
3) Password should have at least one lowercase letter
4) The entered password should have at least one numeral 
5) The entered password should have at least one of the symbols $@#_*
