### ISSUE TITLE
Developing a Keylooger in Python

### ISSUE THREAD

**Issue by srimanikantapalakollu** [sanscript-tech/hacking-tools-scripts#44]
Developing a python script to implement keylogger.

### Tech Stack
- python3

**Comment by 0xpranjal** [comment]
I would like to work on this. Can you please assign me this issue?

**Comment by srimanikantapalakollu** [comment]
Sorry, @Bhard27 actually I want to work on this issue that is the reason I created it.

**Comment by srimanikantapalakollu** [comment]
@yashaswibiyahut please assign it to me.

**Comment by 0xpranjal** [comment]
@srimani-programmer Oh okay, my bad. Sure go ahead!

**Comment by yashaswibiyahut** [comment]
Go for it @srimani-programmer
