### ISSUE TITLE
Check the timing of a program

### ISSUE THREAD

**Issue by yashaswibiyahut** [sanscript-tech/hacking-tools-scripts#48]
Check how long a program has been running and offer the user a chance to cancel tasks that are taking too long.

- [x] C++
- [ ]  Javascript
- [ ] Python

**Comment by AdityaJ7** [comment]
Hi, @yashaswibiyahut I would like to work on this issue with Python.
I will write the script for Windows OS.

**Comment by Nibba2018** [comment]
Hi @yashaswibiyahut , could you be more specific like what kind of program are we talking of here? Is it the python script itself or are we trying to attach to a different process?

**Comment by yashaswibiyahut** [comment]
Python Script to check how long the task is running.

**Comment by Nibba2018** [comment]
@yashaswibiyahut , I am actually not clear which `task` we are talking about here. Can you give an example?

**Comment by eternal-dreamer** [comment]
Can I work on this issue ?

**Comment by yashaswibiyahut** [comment]
Execution time of  task.
You can use time function of time module.

**Comment by Nibba2018** [comment]
@yashaswibiyahut Ok I would like to work on this.

**Comment by TaniaMalhotra** [comment]
@yashaswibiyahut @tejan-singh 
Can I write a C++ script for the same?

**Comment by tejan-singh** [comment]
yes, you can do the same in C++.

**Comment by kuldip11** [comment]
I would like to work on this one in python.  Can I?

**Comment by tejan-singh** [comment]
@kuldip11 issue has been submitted for python. You can work in C, java or javascript

**Comment by Nibba2018** [comment]
@tejan-singh , I would like to work on this in C.

**Comment by yashaswibiyahut** [comment]
Go for it @Nibba2018

**Comment by japneetkaurbhatia** [comment]
I would like to work on this in java
