### ISSUE TITLE
Launching Other Programs from Python

### ISSUE THREAD

**Issue by yashaswibiyahut** [sanscript-tech/hacking-tools-scripts#49]
Use python to run other programs on your computer like Calculator, etc.

**Comment by sanjibansg** [comment]
Can I take up the work ?

**Comment by sanjibansg** [comment]
Before making the initial PR, I wanted to clarify about the Operating System configuration. Also, for Windows, we can use a script like this
```
#Python script to launch anyother program
import os
import subprocess

program="calculator path"
subprocess.Popen(program)
```

Do kindly clarify this before making the initial PR. @yashaswibiyahut

**Comment by yashaswibiyahut** [comment]
yes you can. 
go for it 👍

**Comment by sanjibansg** [comment]
Initial PR made, do kindly review @yashaswibiyahut
