### ISSUE TITLE
Script to scrape IPL scores 

### ISSUE THREAD

**Issue by SANKET7738** [sanscript-tech/hacking-tools-scripts#5]
# Description
Write a script to use web-scraping to get the present day's IPL matches and scores at the moment. you are free to choose to scrape any website you want and you can add more functionality like giving details like Team members, stadium name, etc.

**Comment by AdityaJ7** [comment]
Hi @SANKET7738 I would like to work on this issue

**Comment by tejan-singh** [comment]
you can work on it.
