### ISSUE TITLE
Scrap Top Movies from IMDB 

### ISSUE THREAD

**Issue by yashaswibiyahut** [sanscript-tech/hacking-tools-scripts#52]
Scrap top 250 movies from IMDB and generate a **CSV** file for it

Use [https://www.imdb.com/chart/top/?ref_=nv_mv_250](url) for scraping

**Comment by Nagasuruthika** [comment]
I'd like to take up this issue.

**Comment by tejan-singh** [comment]
Go for it @Nagasuruthika

**Comment by Nibba2018** [comment]
@Nagasuruthika Are you working on this? If not then I would like to take this up.

**Comment by Nibba2018** [comment]
@tejan-singh I would like to take this up if it goes stale.

**Comment by Nagasuruthika** [comment]
@Nibba2018 I'm on it. Should be done  by EOD

**Comment by Nibba2018** [comment]
Okay @Nagasuruthika
