### ISSUE TITLE
It's prime time again! Given a number N, find the largest N digit prime

### ISSUE THREAD

**Issue by balapriyac** [sanscript-tech/hacking-tools-scripts#55]

**Comment by mahimagoyalx** [comment]
I would like to work upon this.

**Comment by balapriyac** [comment]
Pls specify the programming language that you'd like to code in

**Comment by mahimagoyalx** [comment]
> Pls specify the programming language that you'd like to code in

c++

**Comment by harshulab** [comment]
Please assign me this issue, I can solve it using C++.

**Comment by yashaswibiyahut** [comment]
Go for it @mahimagoyalx

**Comment by japneetkaurbhatia** [comment]
Please assign this to me. I can solve this in C++ and python.

**Comment by muddhit** [comment]
Please assign it to me in java @yashaswibiyahut @tejan-singh @balapriyac

**Comment by tejan-singh** [comment]
@japneetbhatia you can work in python

**Comment by tejan-singh** [comment]
@Mukulbaid63 you can work in java

**Comment by muddhit** [comment]
> @Mukulbaid63 you can work in java

@tejan-singh  you haven't assigned me it yet.

**Comment by tejan-singh** [comment]
@Mukulbaid63 when I comment and mention you that means you are assigned and work on this okey.

**Comment by muddhit** [comment]
okay .
