### ISSUE TITLE
Euclid's GCD Algo and relevance in cryptography

### ISSUE THREAD

**Issue by balapriyac** [sanscript-tech/hacking-tools-scripts#56]
- Pls be sure to mention the relevance in cryptography in the README while raising PR

**Comment by ishi0301** [comment]
Please assign me this issue. I would like to work upon this

**Comment by balapriyac** [comment]
Sure, which programming language would you prefer?

**Comment by muddhit** [comment]
Can i work on C or java on this issue?

**Comment by balapriyac** [comment]
Sure

**Comment by Nibba2018** [comment]
@balapriyac This issue seems to be open so I would like to work on this.

**Comment by muddhit** [comment]
@yashaswibiyahut please assign me on this java

**Comment by yashaswibiyahut** [comment]
@Nibba2018 grab it.
@Mukulbaid63 FCFS.

**Comment by muddhit** [comment]
> @Nibba2018 grab it.
> @Mukulbaid63 FCFS.

@yashaswibiyahut i had commented 2 days ago,and i got a reply from @balapriyac but didn't got assigned,so i was the first one to ask

**Comment by muddhit** [comment]
Please assign me to Java for this issue as @Nibba2018  has done for python

**Comment by tejan-singh** [comment]
@Mukulbaid63 you can work in Java.

**Comment by kuldip11** [comment]
I would like to work on this issue in python. Can I?

**Comment by tejan-singh** [comment]
@kuldip11 already submitted for python. Try other languages.
