### ISSUE TITLE
Super easy one! Prime Factorization

### ISSUE THREAD

**Issue by balapriyac** [sanscript-tech/hacking-tools-scripts#57]
- Pls identify use cases of prime factorization in cryptography
- It could be a rather simple one / part of other algorithms as well

**Comment by ishi0301** [comment]
Please assign me this. I would like to work upon this.

**Comment by balapriyac** [comment]
Pls specify the programming language you'd be using

**Comment by muddhit** [comment]
Can i work on Java on this issue?

**Comment by tejan-singh** [comment]
@Mukulbaid63 you can work in java.
