### ISSUE TITLE
Exploring SimPy

### ISSUE THREAD

**Issue by balapriyac** [sanscript-tech/hacking-tools-scripts#58]
- SimPy is a discrete event simulation library in Python
- Create a SimPy model for a simple process such as scheduling, billing counter, ticketing system etc 
- Use features like 'Interrupt' available in SimPy to allow the process to be interrupted by high priority events

**Comment by TaniaMalhotra** [comment]
Hii! 
I would like to take this up!

**Comment by yashaswibiyahut** [comment]
@TaniaMalhotra  did you registered for AOS2020?

**Comment by TaniaMalhotra** [comment]
yes I did

**Comment by TaniaMalhotra** [comment]
@yashaswibiyahut @balapriyac I am sorry for accidentally closing the PR owing to a force push. I have reopened it again, please review 😀
