### ISSUE TITLE
to grab images from a directory, then optimize them for the web.

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#64]
- a image resizing tool

**Comment by TaniaMalhotra** [comment]
Hii! @tejan-singh 
I just created a PR for an issue that was assigned to me
Can I work on this?

**Comment by yashaswibiyahut** [comment]
@TaniaMalhotra  I have already assigned issues to you. Please complete them first then you can work on more.

**Comment by TaniaMalhotra** [comment]
@yashaswibiyahut 
I've created PRs for the two issues assigned to me
Can I start working on this issue?

**Comment by yashaswibiyahut** [comment]
Firstly let them merge then after we will assign another issue yo you @TaniaMalhotra

**Comment by tejan-singh** [comment]
you can now work on this @TaniaMalhotra
