### ISSUE TITLE
to convert tsv to csv file

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#66]

**Comment by aayush-vish** [comment]
@tejan-singh I would like to work on this.
Can I?

**Comment by tejan-singh** [comment]
go ahead ! @aayush-vish

**Comment by sejalshri** [comment]
@tejan-singh i would like to work on this.

**Comment by tejan-singh** [comment]
@sejalshri go for it.

**Comment by Ninjavin** [comment]
Can I work on this in Python @tejan-singh

**Comment by tejan-singh** [comment]
@Ninjavin you can work in python
