### ISSUE TITLE
given a CSV file with an ip address return the geolocation based on the IP address.

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#68]
- hint: you can use request and CSV modules in python.

**Comment by Nibba2018** [comment]
Hey @tejan-singh I would like to work on this issue.

**Comment by Nibba2018** [comment]
Also I am not aware of `Autumn of Open Source` so it would be great if you provide links to know more about it.

**Comment by tejan-singh** [comment]
@are you a participant? have you registered for the event?

**Comment by AdityaJ7** [comment]
@tejan-singh can I take this I just have one more issue assigned to me?

**Comment by kana800** [comment]
Is this up for grab @tejan-singh ?

**Comment by Nibba2018** [comment]
@tejan-singh I haven't registered yet. I cant find the appropriate information anywhere.

**Comment by Nibba2018** [comment]
@tejan-singh is [this](https://aos.sanscript.tech/) the correct link? cause the registration form never loads.

**Comment by tejan-singh** [comment]
@Nibba2018  Working fine.

**Comment by tejan-singh** [comment]
@kana800 have you registered for this event?

**Comment by kana800** [comment]
@tejan-singh yeap! just registered

**Comment by Nibba2018** [comment]
@tejan-singh Registered

**Comment by tejan-singh** [comment]
@kana800 @Nibba2018 have you joined slack channel for this project.

**Comment by kana800** [comment]
> @kana800 @Nibba2018 have you joined slack channel for this project.

No, do we need to?

**Comment by Nibba2018** [comment]
@tejan-singh Nope, there wasn't anything mentioned

**Comment by Nibba2018** [comment]
@tejan-singh  Hello?

**Comment by tejan-singh** [comment]
please go through #130

**Comment by Nibba2018** [comment]
Hi @tejan-singh , I have joined the slack channel can you now assign me this issue?

**Comment by tejan-singh** [comment]
@Nibba2018 It's yours now!
