### ISSUE TITLE
script to send a text message to mobile no. by using https://textbelt.com/

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#69]

**Comment by HaripriyaB** [comment]
Can I work on this issue?

**Comment by HaripriyaB** [comment]
@tejan-singh The textbelt api is available in paid version. And in order to use it for free, need to set up the self hosted server. Any idea how to do it?

**Comment by kana800** [comment]
@HaripriyaB Mentioned in the [DOCs](https://docs.textbelt.com/), **textbelt** has a free API

> key: Your API key (use textbelt to send a free message).

Have you tried using that?

**Comment by HaripriyaB** [comment]
> @HaripriyaB Mentioned in the [DOCs](https://docs.textbelt.com/), **textbelt** has a free API
> 
> > key: Your API key (use textbelt to send a free message).
> 
> Have you tried using that?

For getting our own API key we need to pay for it. But there is another way by hosting the server from local, which I haven't tried yet. Not sure if it'll work

**Comment by kana800** [comment]
@HaripriyaB, What I meant is that there is a free API called `textbelt`. You can **send 1 free message** using the free API and _YES_ to get your own API key we need to pay for it. I think you can just use the **free API**.
<details> 
  <summary>sample code _spoiler_ </summary>

```python
import requests

ur_num="" #enter your number here
resp = requests.post('https://textbelt.com/text', {
  'phone': ur_num,
  'message': 'Hello world',
  'key': 'textbelt',
})
print(resp.json())
```
![WhatsApp Image 2020-10-22 at 09 24 16](https://user-images.githubusercontent.com/64830745/96822912-ccbbe980-1448-11eb-8433-114a4a701218.jpeg)



</details>

**_EDIT:
the code is obtained from the [DOC](https://docs.textbelt.com/)_**

**Comment by HaripriyaB** [comment]
> @HaripriyaB, What I meant is that there is a free API called `textbelt`. You can **send 1 free message** using the free API and _YES_ to get your own API key we need to pay for it. I think you can just use the **free API**.
> <details> 
>   <summary>sample code _spoiler_ </summary>
> 
> ```python
> import requests
> 
> ur_num="" #enter your number here
> resp = requests.post('https://textbelt.com/text', {
>   'phone': ur_num,
>   'message': 'Hello world',
>   'key': 'textbelt',
> })
> print(resp.json())
> ```
> ![WhatsApp Image 2020-10-22 at 09 24 16](https://user-images.githubusercontent.com/64830745/96822912-ccbbe980-1448-11eb-8433-114a4a701218.jpeg)
> 
> 
> 
> </details>
> 
> **_EDIT:
> the code is obtained from the [DOC](https://docs.textbelt.com/)_**

I tried in postman, this one free message per day API but I was getting some error. Can you tell me the format of the phone number you provided. Is it +91 prefix??

**Comment by kana800** [comment]
@HaripriyaB  your number should be in the `E.164 format`. More information [here](https://docs.textbelt.com/faq#how-should-i-format-my-phone-numbers) 
eg:
`+919555536736`

**Comment by HaripriyaB** [comment]
> @HaripriyaB your number should be in the `E.164 format`. More information [here](https://docs.textbelt.com/faq#how-should-i-format-my-phone-numbers)
> eg:
> `+919555536736`

Thank you. So sorry to bother you 😅

**Comment by kana800** [comment]
@HaripriyaB No worries 😄
