### ISSUE TITLE
Convert image to text

### ISSUE THREAD

**Issue by SANKET7738** [sanscript-tech/hacking-tools-scripts#7]
# Description

Write a script to convert an image to text. basically, a script to perform OCR. the text from the image must be stored in a `.txt` file.

**Comment by Namyalg** [comment]
I would like to work on this

**Comment by SANKET7738** [comment]
assigned to you @Namyalg

**Comment by Namyalg** [comment]
I have added the README and made the changes

**Comment by SANKET7738** [comment]
Just add a screenshot of the output in the README. Please refer to the contribution guidelines mentioned on the Slack channel.
