### ISSUE TITLE
to convert JSON to YAML

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#70]
- you need to take input from a JSON file and save the output to another file.

**Comment by AdityaJ7** [comment]
Hi @tejan-singh can I take this issue with Python?

**Comment by tejan-singh** [comment]
@AdityaJ7 it seems like you have 2 already assigned issues. If you want to work on this issue then I need to unassign you from any of your past assigned issues. Please clearify what would you like to do?

**Comment by AdityaJ7** [comment]
> @AdityaJ7 it seems like you have 2 already assigned issues. If you want to work on this issue then I need to unassign you from any of your past assigned issues. Please clarify what would you like to do?

ok unassign me from any one of those two, because I have completed this one, but after submitting a Pr for this I can be assigned back to the one from which I am removed right?? @tejan-singh

**Comment by tejan-singh** [comment]
yes sure!
