### ISSUE TITLE
Beginner-friendly! Generate random data points; Implement K Means clustering from Scratch

### ISSUE THREAD

**Issue by balapriyac** [sanscript-tech/hacking-tools-scripts#71]
- pls do not use scikit-learn

**Comment by Divyansh-20** [comment]
@balapriyac can this be assigned to me?

**Comment by tejan-singh** [comment]
Go for it @Divyansh-20

**Comment by Mishrasubha** [comment]
Can I work on it? I would start  working on it from 27th though.

**Comment by balapriyac** [comment]
Sure, but once you're assigned an issue, you have 7 days to work on it and
after that it would be re-assigned.
So, pls plan accordingly when you want the issue to be assigned

**Comment by Mishrasubha** [comment]
ok please assign it to me on 27th.

**Comment by Mishrasubha** [comment]
Assign this to me please.

**Comment by balapriyac** [comment]
Sure!

**Comment by japneetkaurbhatia** [comment]
Hey, Assign this to me

**Comment by tejan-singh** [comment]
@japneetbhatia which language you like to work on?

**Comment by japneetkaurbhatia** [comment]
@tejan-singh Python

**Comment by tejan-singh** [comment]
@japneetbhatia  you can work in python.
