### ISSUE TITLE
Get Meaning of a Word

### ISSUE THREAD

**Issue by yashaswibiyahut** [sanscript-tech/hacking-tools-scripts#79]
Create a Script to get the Meaning of a Word straight from CLI.
Make use of APIs to get the meaning of a word.

**Comment by AdityaJ7** [comment]
> Create a Script to get the Meaning of a Word straight from CLI.
> Make use of APIs to get the meaning of a word.

Hi @yashaswibiyahut can i work on this issue?

**Comment by yashaswibiyahut** [comment]
Go for it @AdityaJ7
