### ISSUE TITLE
create a simple port scanner to scan for open ports for server (with multi-threading)

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#9]

**Comment by eternal-dreamer** [comment]
I want to work on this issue.

**Comment by tejan-singh** [comment]
yes you can work on this.

**Comment by kana800** [comment]
can i work on this?

**Comment by tejan-singh** [comment]
@kana800 If you like to contribute then you can but I will not assign you this assignment. But yes, I will accept your PR if you follow contribution guidelines.

**Comment by kana800** [comment]
@tejan-singh no one seems to be working on this, maybe because it has the **assigned** tag still.  I will create a simple port scanner and send a PR.

Thanks!
>If you like to contribute then you can but I will not assign you this assignment. But yes, I will accept your PR if you follow contribution guidelines.

**Comment by Nibba2018** [comment]
@tejan-singh , I would like to work on this if it's open.
