### ISSUE TITLE
Implement Simple Linear Regression (Univariate Linear Regression)

### ISSUE THREAD

**Issue by balapriyac** [sanscript-tech/hacking-tools-scripts#91]
- Use NumPy; not scikit-learn
- Use either randomly generated dataset or simple dataset from kaggle
- Pls include EDA section in your notebook
- Comment on inferences and metrics for evaluation

**Comment by sujal111** [comment]
Please assign this issue to me. I would love to work on it

**Comment by balapriyac** [comment]
sure, I'm assigning, pls be sure to include all relevant details cited above

**Comment by balapriyac** [comment]
@sujal111 just a small clarification required, could you pls confirm that you've already registered for AOS '20
Because we are unable to find you in the Slack channel assigned for this project

**Comment by sujal111** [comment]
@balapriyac I have joined now.

**Comment by balapriyac** [comment]
Thanks, pls be sure to follow the contribution guidelines going forward

**Comment by japneetkaurbhatia** [comment]
Can I work on this using python ?

**Comment by tejan-singh** [comment]
@japneetbhatia you can work in python.
