### ISSUE TITLE
amazon price tracker! Sale Session Special!!

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#97]
You need to build a script that will ask for your budget and the product link and notify you when the product price drops,

**Comment by Namyalg** [comment]
I would like to work on this in Python

**Comment by Namyalg** [comment]
@tejan-singh , can we also raise issues and work on them?

**Comment by yashaswibiyahut** [comment]
@Namyalg  I have already assigned issues to you. Please complete them first then you can work on more.
Yes, you can but after creating wait for mentors to assign that issue to you then after you can work on that issue.

**Comment by Namyalg** [comment]
I have created a PR for the issues that were assigned to me

Namya LG
