### ISSUE TITLE
a python script to notify you to take rest after certain time.

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#99]

**Comment by kana800** [comment]
can i work on this?

**Comment by yashaswibiyahut** [comment]
@kana800  did you participate in AOS2020

**Comment by Tejas1510** [comment]
Can I work on this @yashaswibiyahut ?

**Comment by kana800** [comment]
@yashaswibiyahut  I registered for the event

**Comment by tejan-singh** [comment]
@kana800 have you got the confirmation mail? have you joined the slack channel for the event??

**Comment by kana800** [comment]
@tejan-singh  No I didnt get a confirmation mail

**Comment by tejan-singh** [comment]
@kana800 go through #130

**Comment by tejan-singh** [comment]
@Tejas1510 you can work on this.

**Comment by Tejas1510** [comment]
@tejan-singh Sir I have raised a PR can you please look into it.
